[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "djangoProject1.settings"
python_files = [
    "tests*.py",
    "tests_*.py",
    "*_tests.py",
    "*tests.py",
    "test*.py",
    "test_*.py",
    "*_test.py",
    "*test.py",
]
addopts = "--reuse-db --disable-socket --allow-unix-socket --allow-hosts=127.0.0.1,127.0.1.1,::1,localhost"
timeout = 60
